In [1]:
import os
import sys
import csv
import operator
import time
import datetime
import platform

In [2]:
def writeText(text, path, mode = 'w'):
    with open (path, mode, encoding = 'utf-8') as textout:
        textout.write((text))
        
def writeJson(json, path, mode = 'w'):
    with open(path, mode) as file:
        file.write(json.dumps(json))
        
def writeCsv(listOut, outputFile):
    with open (outputFile, "w", newline='', encoding = 'utf-8') as outputfile:
        writer = csv.writer(outputfile, delimiter = ",")
        for element in listOut:
            writer.writerow(element)
            
def getTxt(path):
    return open(path, 'r').read()

def getCsv(path, delim = ','):
    list_return = []
    with open (path, encoding = 'utf-8') as file:
        csvreader = csv.reader(file, delimiter = delim)        
        for i, line in enumerate(csvreader):
            list_return.append(line)
    return list_return

In [3]:
def getFloatCsv(path, delim = ','):
    list_return = []
    with open (path, encoding = 'utf-8') as file:
        csvreader = csv.reader(file, delimiter = delim)        
        for i, line in enumerate(csvreader):
            list_return.append([float(x) for x in line])
    return list_return

### data import

In [4]:
if platform.system() == 'Windows':
    feat = getFloatCsv('..\\output\\feat.csv')
else:
    feat = getFloatCsv('../output/feat.csv')

In [5]:
if platform.system() == 'Windows':
    label = getCsv('..\\output\\labels.csv')
else:
    label = getCsv('../output/labels.csv')

### numpy prep

In [6]:
import numpy as np

In [7]:
X = np.array(feat)

### sklearn prep

In [8]:
from sklearn.preprocessing import MultiLabelBinarizer

In [9]:
multilabel_binarizer = MultiLabelBinarizer()
multilabel_binarizer.fit(label)
y = multilabel_binarizer.transform(label)

In [10]:
X, y

(array([[-0.40620422,  0.37869263,  0.58084106, ...,  0.03137207,
          0.64916992, -1.32333374],
        [-0.50666809,  0.45892334,  0.73953247, ..., -0.08215332,
          1.0402832 , -1.47055054],
        [-0.44416809,  0.43939209,  0.61599731, ..., -0.01086426,
          0.69067383, -1.39877319],
        ...,
        [-0.52600098,  0.26296997,  1.75932312, ...,  0.03231812,
          1.67541504, -2.25292969],
        [-0.63769531,  0.25286865,  1.96574402, ...,  0.20346069,
          1.8770752 , -2.28613281],
        [-0.57519531,  0.2333374 ,  1.84220886, ...,  0.27474976,
          1.52746582, -2.21435547]]),
 array([[1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 1],
        [0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0

### RandomForest

In [11]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

In [12]:
clf = RandomForestClassifier(n_estimators=100, max_depth=2,random_state=0)
clf.fit(X, y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=2, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [13]:
clf.feature_importances_

array([0.00236986, 0.00415934, 0.00068056, 0.00423496, 0.        ,
       0.        , 0.01951557, 0.00230582, 0.        , 0.00155142,
       0.        , 0.        , 0.00385007, 0.        , 0.        ,
       0.00152141, 0.        , 0.00068213, 0.00275143, 0.        ,
       0.00467187, 0.01064845, 0.00966599, 0.00373415, 0.00122965,
       0.        , 0.015385  , 0.00097634, 0.        , 0.01053773,
       0.        , 0.00293458, 0.00534544, 0.        , 0.00051289,
       0.00420868, 0.00342943, 0.00344389, 0.0214024 , 0.00348498,
       0.        , 0.00086631, 0.        , 0.01697645, 0.        ,
       0.00178085, 0.        , 0.00335762, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.00727435, 0.0056932 ,
       0.00079957, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.00038488, 0.        , 0.        , 0.00108114,
       0.        , 0.00726065, 0.00282825, 0.        , 0.02360783,
       0.        , 0.00129869, 0.        , 0.00352502, 0.     

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>